# Generated by Django 5.2.6 on 2025-10-01 13:17

import django.utils.timezone
import imageprocessor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_type', models.CharField(choices=[('jacket', 'Jacket'), ('shirt', 'Shirt'), ('pants', 'Pants'), ('dress', 'Dress'), ('other', 'Other')], help_text='Type of clothing item', max_length=20)),
                ('original_image', models.ImageField(help_text='Original uploaded image', upload_to=imageprocessor.models.upload_to_original)),
                ('processed_image', models.ImageField(blank=True, help_text='AI processed image', null=True, upload_to=imageprocessor.models.upload_to_processed)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Processing status', max_length=20)),
                ('processing_prompt', models.TextField(help_text='Prompt used for AI processing')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('openai_response_id', models.CharField(blank=True, help_text='OpenAI API response ID', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Processed Image',
                'verbose_name_plural': 'Processed Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
