# Generated by Django 5.2.6 on 2025-10-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='clothing_type',
            field=models.CharField(choices=[('jacket', 'Jacket'), ('shirt', 'Shirt'), ('pants', 'Pants'), ('dress', 'Dress'), ('sweater', 'Sweater'), ('hoodie', 'Hoodie'), ('coat', 'Coat'), ('blouse', 'Blouse'), ('skirt', 'Skirt'), ('shorts', 'Shorts'), ('other', 'Other')], help_text='Type of clothing item', max_length=20),
        ),
    ]
