# Generated by Django 5.2.6 on 2025-10-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0002_alter_processedimage_clothing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='gpt4_analysis',
            field=models.TextField(blank=True, help_text='GPT-4 Vision analysis of the image', null=True),
        ),
    ]
