# Generated by Django 5.2.6 on 2025-10-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0003_processedimage_gpt4_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='clothing_type',
            field=models.CharField(choices=[('jacket', 'Jacket'), ('shirt', 'Shirt'), ('tshirt', 'Tshirt'), ('pants', 'Pants'), ('dress', 'Dress'), ('sweater', 'Sweater'), ('hoodie', 'Hoodie'), ('coat', 'Coat'), ('blouse', 'Blouse'), ('skirt', 'Skirt'), ('shorts', 'Shorts'), ('shoes', 'Shoes'), ('other', 'Other')], help_text='Type of clothing item', max_length=20),
        ),
    ]
