# Generated by Django 5.2.6 on 2025-10-03 07:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0004_alter_processedimage_clothing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this outfit', max_length=200)),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('business', 'Business'), ('party', 'Party'), ('sport', 'Sport'), ('evening', 'Evening'), ('weekend', 'Weekend'), ('travel', 'Travel'), ('date', 'Date'), ('work', 'Work')], help_text='Occasion this outfit is suitable for', max_length=20)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Season')], help_text='Season this outfit is suitable for', max_length=20)),
                ('style_description', models.TextField(help_text='AI-generated description of the outfit')),
                ('color_scheme', models.JSONField(blank=True, help_text='Color scheme analysis', null=True)),
                ('style_tags', models.JSONField(blank=True, help_text='Style tags for this outfit', null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence score for this recommendation (0-1)')),
                ('is_favorite', models.BooleanField(default=False, help_text='Mark as favorite outfit')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='User rating (1-5)', null=True)),
                ('last_worn', models.DateField(blank=True, help_text='Last time this outfit was worn', null=True)),
                ('wear_count', models.PositiveIntegerField(default=0, help_text='Number of times worn')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outfit Recommendation',
                'verbose_name_plural': 'Outfit Recommendations',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('outerwear', 'Outerwear'), ('dress', 'Dress')], help_text='Role of this item in the outfit', max_length=20)),
                ('match_score', models.FloatField(default=0.0, help_text='How well this item matches the outfit (0-1)')),
                ('style_notes', models.TextField(blank=True, help_text='AI notes about this item in the outfit', null=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageprocessor.outfitrecommendation')),
            ],
            options={
                'verbose_name': 'Outfit Item',
                'verbose_name_plural': 'Outfit Items',
            },
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom name for this item', max_length=200)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('outerwear', 'Outerwear'), ('dress', 'Dress')], help_text='Category of clothing item', max_length=20)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('navy', 'Navy'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('beige', 'Beige'), ('cream', 'Cream'), ('multicolor', 'Multicolor'), ('other', 'Other')], help_text='Primary color of the item', max_length=20)),
                ('brand', models.CharField(blank=True, help_text='Brand name', max_length=100, null=True)),
                ('size', models.CharField(blank=True, help_text='Size of the item', max_length=20, null=True)),
                ('material', models.CharField(blank=True, help_text='Material/fabric type', max_length=100, null=True)),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('business', 'Business'), ('party', 'Party'), ('sport', 'Sport'), ('evening', 'Evening'), ('weekend', 'Weekend'), ('travel', 'Travel')], default='casual', help_text='Suitable occasion for this item', max_length=20)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Season')], default='all', help_text='Season this item is suitable for', max_length=20)),
                ('style_description', models.TextField(blank=True, help_text='AI-generated style description', null=True)),
                ('color_palette', models.JSONField(blank=True, help_text='Extracted color palette', null=True)),
                ('style_tags', models.JSONField(blank=True, help_text='Style tags for matching', null=True)),
                ('is_favorite', models.BooleanField(default=False, help_text='Mark as favorite item')),
                ('last_worn', models.DateField(blank=True, help_text='Last time this item was worn', null=True)),
                ('wear_count', models.PositiveIntegerField(default=0, help_text='Number of times worn')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_item', to='imageprocessor.processedimage')),
            ],
            options={
                'verbose_name': 'Wardrobe Item',
                'verbose_name_plural': 'Wardrobe Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='outfitrecommendation',
            name='items',
            field=models.ManyToManyField(related_name='outfits', through='imageprocessor.OutfitItem', to='imageprocessor.wardrobeitem'),
        ),
        migrations.AddField(
            model_name='outfititem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageprocessor.wardrobeitem'),
        ),
        migrations.AlterUniqueTogether(
            name='outfititem',
            unique_together={('outfit', 'item')},
        ),
    ]
